api/urls.py
from rest_framework import routers


from api.views import ProductViewSet

app_name = "api"

router = routers.DefaultRouter()

router.register("products", ProductViewSet, basename='products')

urlpatterns = [
]




urlpatterns.extend(router.urls)

products/urls.py
from django.urls import path

from products.views import ProductsListView

app_name = 'products'

urlpatterns = [
    path('', ProductsListView.as_view(), name='products')
]

src/urls.py
from django.urls import path


from src.views import ShowMainPage, ShowResult

app_name = 'src'

urlpatterns = [
    path('', ShowMainPage.as_view(), name='main'),
    path('result/', ShowResult.as_view(), name='result'),
]

task/urls.py
from django.contrib import admin
from django.urls import include, path

urlpatterns = [
    path('admin/', admin.site.urls),
    path('api/', include('api.urls', namespace='api')),
    path('', include('src.urls', namespace='src')),
    path('products/', include('products.urls', namespace='products'))
]

api/models.py
from django.db import models

# Create your models here.

products/models.py
from django.db import models


class Product(models.Model):
    title = models.CharField(max_length=200, verbose_name="Название товара")
    price = models.PositiveIntegerField(verbose_name="Стоимость товара")
    discounted_price = models.PositiveIntegerField(
        verbose_name="Стоимость товара со скидкой"
    )
    rating = models.FloatField( verbose_name="Рейтинг")
    reviews = models.PositiveIntegerField(verbose_name="Количество отзывов")

    class Meta:
        db_table = "products"
        verbose_name = "Продукт"
        verbose_name_plural = "Продукты"

    def __str__(self):
        return str(self.title)

src/models.py
from django.db import models

# Create your models here.

src/forms.py
# from django import forms


# class InputForm(forms.Form):
#     data = forms.CharField(max_length=100, label="Введите данные для поиска")

api/views.py
from rest_framework import viewsets
from django_filters.rest_framework import DjangoFilterBackend

from api.filters import ProductFilterAPI
from api.serializers import ProductsSerializer
from products.models import Product


class ProductViewSet(viewsets.ModelViewSet):
    serializer_class = ProductsSerializer
    queryset = Product.objects.all()
    filter_backends = [DjangoFilterBackend]
    filterset_class = ProductFilterAPI

products/views.py
from django_filters.views import FilterView


from products.filters import ProductFitlter
from products.models import Product


class ProductsListView(FilterView):
    model = Product
    template_name = "products/products.html"
    filterset_class = ProductFitlter
    context_object_name = "products_list"

    def get_context_data(self, **kwargs):
        import plotly.graph_objects as go

        context = super().get_context_data(**kwargs)
        # queryset = self.get_queryset()

        filtered_queryset = self.filterset.qs

        if filtered_queryset.exists():
            titles = [item.title for item in filtered_queryset]
            prices = [item.price for item in filtered_queryset]

            fig = go.Figure(data=[go.Bar(x=titles, y=prices)])
            fig.update_layout(
                title="Гистограма распределения 'Цены' и 'Количества товара'",
                xaxis_title="Название товара",
                yaxis_title="Цена",
            )
            context["plot_div_histogram"] = fig.to_html(
                full_html=False, default_height=300
            )
        else:
            context["plot_div_histogram"] = None

        if filtered_queryset.exists():
            discount = [
                int(((item.price - item.discounted_price) / item.price * 100))
                for item in filtered_queryset
            ]
            rating = [item.rating for item in filtered_queryset]

            line_trace = go.Scatter(
                x=rating, y=discount, mode="markers", name="Линейная диаграма"
            )

            fig = go.Figure(data=[line_trace])
            fig.update_layout(
                title="График линейный - влияние 'Размера скидки' на 'Рейтинг товара'",
                xaxis_title="Рейтинг",
                yaxis_title="Размер скидки",
            )
            context["plot_div_line"] = fig.to_html(full_html=False, default_height=300)
        else:
            context["plot_div_line"] = None

        return context

src/views.py
from django.shortcuts import redirect

from django.views.generic import TemplateView

from products.models import Product
from src.parser import extract_data


class ShowMainPage(TemplateView):
    template_name = "src/index.html"

    def post(self, request, *args, **kwargs):
        if request.method == "POST":
            data = request.POST.get("data")
            request.session["saved_data"] = data
            return redirect("src:result")
        return super().get(request, *args, **kwargs)


class ShowResult(TemplateView):
    template_name = "src/result.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        context["saved_data"] = self.request.session.get("saved_data")
        element = self.request.session.get("saved_data")
        parser_data = extract_data(element)
        context["parser_data"] = parser_data

        for item in parser_data:
            new_object = Product(
                title=item[0],
                price=int(item[2]),
                discounted_price=int(item[1]),
                rating=float(item[3]),
                reviews=int(item[4]),
            )
            new_object.save()

        return context

products/templates/products/products.html
{% extends 'base.html' %}
{% load static %}
{% block content %}


<div class='container'>
  <h3>ДАННЫЕ</h3>
<h4> Полученные данные представлены в 3-ех фреймах: Гистограмма, Линейный график, Таблица с данными </br>
  Все данные интерактивны и динамически обновляются.
    </h4>
  {% if plot_div_histogram %}
      <div>
          {{ plot_div_histogram|safe }}
      </div>
  {% else %}
      <p>Нет данных для отображения графика.</p>
  {% endif %}
  {% if plot_div_line %}
      <div>
          {{ plot_div_line|safe }}
      </div>
  {% else %}
      <p>Нет данных для отображения графика.</p>
  {% endif %}

  <table class="table">
    <thead>
      <tr>
        <th scope="col">#</th>
        <th scope="col">Title</th>
        <th scope="col">Discounted_price</th>
        <th scope="col">Price</th>
        <th scope="col">Rating</th>
        <th scope="col">Reviews</th>
      </tr>
      <tr>
        <th scope="col">&</th>
        <th scope="col">Title</th>
        <th scope="col">
        <div class="btn-group">
          <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Сортировка цен ↑↓
          </button>
          <ul class="dropdown-menu">
              <li><a class="dropdown-item">
                <form method="get">
                  {{ filter.form.ordering_price_disc }}
                  <button type="submit">Сортировка ↑ ↓</button>
                </form>
              </li>
              <li><a class="dropdown-item">
                <form method="get">
                  {{ filter.form.range_price_disc }}
                  <button type="submit">Диапазон → ←</button>
                </form>
              </li>           
          </ul>
          </div>
            
        </th>
        <th scope="col">
        <div class="btn-group">
          <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Сортировка цен ↑↓
          </button>
          <ul class="dropdown-menu">
              <li><a class="dropdown-item">
                <form method="get">
                  {{ filter.form.ordering_price }}
                  <button type="submit">Сортировка ↑ ↓</button>
                </form>
              </li> 
              <li><a class="dropdown-item">
                <form method="get">
                  {{ filter.form.range_price }}
                  <button type="submit">Диапазон → ←</button>
                </form>
              </li>          
          </ul>
          </div>
        </th>
        <th scope="col">
          <div class="btn-group">
          <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Фильтр по рейтингу
          </button>
          <ul class="dropdown-menu">
              <li><a class="dropdown-item">
                <form method="get">
                  {{ filter.form.min_rating }}
                  <button type="submit">Рейтинг больше или равен значению</button>
                </form>
              </li>
            <li><a class="dropdown-item">
                <form method="get">
                  {{ filter.form.max_rating }}
                  <button type="submit">Рейтинг меньше или равен значению</button>
                </form>
              </li>
              <li><a class="dropdown-item">
                <form method="get">
                  {{ filter.form.ordering_rating }}
                  <button type="submit">Сортировка ↑ ↓</button>
                </form>
              </li>
          </ul>
        </div>
          </th>
        <th scope="col">
          <div class="btn-group">
          <button class="btn btn-secondary btn-sm dropdown-toggle" type="button" data-bs-toggle="dropdown" aria-expanded="false">
            Фильтр по количеству отзывов
          </button>
          <ul class="dropdown-menu">
            <li><a class="dropdown-item">
                <form method="get">
                  {{ filter.form.min_reviews }}
                  <button type="submit">Отзывов больше или равно значению</button>
                </form>
              </li>
            <li><a class="dropdown-item">
                <form method="get">
                  {{ filter.form.max_reviews }}
                  <button type="submit">Отзывов меньше или равно значению</button>
                </form>
              </li>
              <li><a class="dropdown-item">
                <form method="get">
                  {{ filter.form.ordering_reviews }}
                  <button type="submit">Сортировка ↑ ↓</button>
                </form>
              </li>
          </ul>
        </div>
          </th>
      </tr>

    </thead>
    <tbody>
      {% for x in products_list %}
      <tr>
        <th scope="row">{{ x.id }}</th>
        <td>{{ x.title }}</td>
        <td>{{ x.discounted_price }}</td>
        <td>{{ x.price }}</td>      
        <td>{{ x.rating }}</td>
        <td>{{ x.reviews }}</td>
      </tr>    
      {% endfor %}
    </tbody>
  </table>
</div>

{% endblock content %}

src/templates/src/index.html
{% extends 'base.html' %}

{% block content %}
<div class='container'>
    <h3>ГЛАВНАЯ</h3>
    <h3> Введите запрос и нажмите кнопку - Отправить.<br>
        Запустится парсер, который обработает запрос и сохранит данные в базе данных.<br>
        Парсер написан с помощью Selenium, для работы потребуется GoogleChrome Browser.<br>
        Время работы парсера - около 40-45 секунд.<br>
        После работы парсера, вы будете переенаправлены на страницу промежуточных результатов.<br>
        Сохранённые данные так-же будут доступны по API.
        </h3>
    <form method='post'>
        {% csrf_token %}
        <p>Введите запрос: <br> <input  name='data'/></p>
        <input type='submit' value='Отправить' />
    </form>
    <br>
    <br>
    <h3>
        <a href="{% url 'products:products' %}">Посмотреть уже имеющиеся данные(при наличии)</a>
    </h3>
    <h3>
        <a href="api/products/">Перейти к API</a>
    </h3>
</div>

{% endblock content %}

src/templates/src/result.html
{% extends 'base.html' %}

{% block content %}
<div class='container'>
<h3>ПРЕДВАРИТЕЛЬНЫЕ РЕЗУЛЬТАТЫ</h3>
<h3> Скрипт отработал по запросу - "{{ saved_data }}"" - <br>
     Теперь можно просмотреть результаты.
</h3>
<h3>
    <a href="{% url 'products:products' %}">Перейти на страницу с товарами</a>
</h3>
</div>
{% endblock content %}

templates/base.html
<!doctype html>
<html lang="ru">
  <head>

    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">


    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-EVSTQN3/azprG1Anm3QDgpJLIm9Nao0Yz1ztcQTwFspd3yD65VohhpuuCOmLASjC" crossorigin="anonymous">

  </head>
  <body>

    {% block content %}
    
    {% endblock content %}

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>

  </body>
</html>